Id: Microsoft.WSL2.Kernel
Version: 5.4.42
Name: WSL2 Kernel Update
Publisher: Microsoft Corporation
Homepage: https://docs.microsoft.com/en-gb/windows/wsl/wsl2-kernel
License: Copyright (C) Microsoft Corporation
Description: The WSL 2 is a new version of the architecture in WSL that changes how Linux distributions interact with Windows. WSL 2 has the primary goals of increasing file system performance and adding full system call compatibility.
Installers:
  - Arch: x64
    Url: https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi
    InstallerType: MSI
    Sha256: f4833159d00077e160c4b87ca4c4066da0b20bec69331cd414a6cb62bd88de70
